apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-1
  labels:
    release: example-1
spec:
  replicas: 1
  selector:
    matchLabels:
      release: example-1
  template:
    metadata:
      labels:
        release: example-1
    spec:
      containers:
        - name: main
          image: sikalabs/hello-world-server
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 50Mi
