apiVersion: v1
kind: Service
metadata:
  name: example-1
  labels:
    release: example-1
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    release: example-1
