apiVersion: v1
kind: Service
metadata:
  name: argocd-example-v1
  labels:
    release: argocd-example-v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    release: argocd-example-v1
